spring:
    freemarker:
        allow-request-override: true
        cache: false
        check-template-location: true
        charset: utf-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .ftl
        template-loader-path: classpath:/templates/
        request-context-attribute: request
    mvc:
        static-path-pattern: /static/**


druid:
    datasource:
        username: root  #数据库用户名
        password: mysql      #数据库密码
        driver-class-name: com.mysql.jdbc.Driver  #数据库驱动
        url: jdbc:mysql://127.0.0.1:3306/hera?characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&allowMultiQueries=true
        initial-size: 5    #初始化连接池数量
        min-idle: 1        #最小生存连接数
        max-active: 32     #最大连接池数量
        max-wait: 5000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        time-between-connect-error-millis: 60000  # Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接，单位是毫秒
        min-evictable-idle-time-millis: 300000  # 连接保持空闲而不被驱逐的最长时间，单位是毫秒
        test-while-idle: true    #申请连接的时候,如果检测到连接空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        test-on-borrow: true    #申请连接时执行validationQuery检测连接是否有效
        test-on-return: false   # 归还连接时执行validationQuery检测连接是否有效
        connection-init-sqls: 'set names utf8mb4'
        validation-query: select 1                #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
        validation-query-timeout: 1                #单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
        log-abandoned: true
        stat-mergeSql: true
        filters: stat,wall,log4j
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


server:
    port: 8899
    context-path: /

clean:
    path: ${server.context-path}

mybatis:
    configuration:
        mapUnderscoreToCamelCase: true


---
## 开发环境
spring:
    profiles: dev

---
## 日常环境  通常与开发环境一致
spring:
    profiles: daily

